server:
  application:
    name: registry-service
  port: ${PORT:8761}

security:
  basic:
    enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0