spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

security:
    user:
        name: admin
        password: admin
        role: USER,ADMIN
        
#eureka:
#  client:
#    fetchRegistry: false
#    registerWithEureka: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/registry

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/